// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwrL7TWkETK7sGe_QUnwmz32v68XUNzo0',
    appId: '1:257466989348:web:8348f0b05c8d80b712d1b1',
    messagingSenderId: '257466989348',
    projectId: 'aapg-96b6e',
    authDomain: 'aapg-96b6e.firebaseapp.com',
    storageBucket: 'aapg-96b6e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChwn5T9C7xjnbZnjehJRcSiyYy4mXd4yQ',
    appId: '1:257466989348:android:8eeea4ea6c54d54212d1b1',
    messagingSenderId: '257466989348',
    projectId: 'aapg-96b6e',
    storageBucket: 'aapg-96b6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHm2H05dgPDsIUZaL4fyMNVWW405U1upU',
    appId: '1:257466989348:ios:034c0fe9b0199e2c12d1b1',
    messagingSenderId: '257466989348',
    projectId: 'aapg-96b6e',
    storageBucket: 'aapg-96b6e.firebasestorage.app',
    iosBundleId: 'com.example.cleanApgApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHm2H05dgPDsIUZaL4fyMNVWW405U1upU',
    appId: '1:257466989348:ios:034c0fe9b0199e2c12d1b1',
    messagingSenderId: '257466989348',
    projectId: 'aapg-96b6e',
    storageBucket: 'aapg-96b6e.firebasestorage.app',
    iosBundleId: 'com.example.cleanApgApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwrL7TWkETK7sGe_QUnwmz32v68XUNzo0',
    appId: '1:257466989348:web:bd6fe1c5af35bb6a12d1b1',
    messagingSenderId: '257466989348',
    projectId: 'aapg-96b6e',
    authDomain: 'aapg-96b6e.firebaseapp.com',
    storageBucket: 'aapg-96b6e.firebasestorage.app',
  );

}